### ISSUE TITLE
Compare with "Exploring the structure of a real-time, arbitrary neural artistic stylization network" method

### ISSUE THREAD

**Issue by ripplexyz** [irasin/Structure-emphasized-Multimodal-Style-Transfer#1]
Hi Sin,

Great work with SEMST. For past couple of weeks I am learning Style Inference and your work is really helpful.

There is a particular work by Jonathon Shlens, published in 2017 - "Exploring the structure of a real-time, arbitrary neural artistic stylization network" https://arxiv.org/abs/1705.06830 which uses different method to produce the result.

Official implementation -- https://github.com/magenta/magenta/tree/master/magenta/models/arbitrary_image_stylization

Did you got chance to compare your results with this?

**Comment by irasin** [comment]
Hi, @vegadvarsha30 

Thank you for your attention.

I'm very very sorry that I'm working on DNN on-device inference engine recently, So I guess I have no time to do style transfer now.

You can try it if you have interests. Good luck and may you succeed.
