### ISSUE TITLE
Is this applicable in real-time scenarios?

### ISSUE THREAD

**Issue by AyushExel** [irasin/Structure-emphasized-Multimodal-Style-Transfer#3]
Hi. Great work on implementing this! I wanted to know if this can be used for real-time scenarios like a webcam?

**Comment by irasin** [comment]
Unfortunately, I don't think it is possible to do real-time style transfer.
Here are some results(image transfer time[second] of different input sizes) based on a 1080Ti GPU. And the AdaIN is the fastest.

![image](https://user-images.githubusercontent.com/25549893/151706869-afd45a06-d24c-416e-ba80-18e5c5f6bf5e.png)
