### ISSUE TITLE
download vgg_path error

### ISSUE THREAD

**Issue by wangling9010** [irasin/Structure-emphasized-Multimodal-Style-Transfer#4]
when i am trying to train it ,the vgg weight can't be downloaded.
i want to kown if the download url is available?  and how to fix it?
thanks very much!!!

the code :
![image](https://user-images.githubusercontent.com/56386599/151651344-b6a48001-c263-4f57-9fb0-0ae98adccd89.png)

the error:
![image](https://user-images.githubusercontent.com/56386599/151651355-c2d0e9dc-0a78-4441-b775-b999b3b61bd5.png)

**Comment by irasin** [comment]
Maybe you need to set up your proxy on your server because I put all my data on google driver./
