### ISSUE TITLE
数据集处理出错

### ISSUE THREAD

**Issue by wangling9010** [irasin/Structure-emphasized-Multimodal-Style-Transfer#5]
作者您好，看了您的方法和效果感觉特别棒！我想尝试着自己训练试试，但是在实现过程中遇到问题如下：

我的content数据集采用的是coco
style数据集是自己的，使用了6张图片
但是训练过程中发现由于使用了zip函数，只生成了6对图片对，无法完成训练。
请问您的style数据集是如何处理的？或者我该如何解决这个问题，十分感谢！！

![image](https://user-images.githubusercontent.com/56386599/151656286-ee8d8029-f049-40e1-b79b-2883b3a79c3f.png)

![image](https://user-images.githubusercontent.com/56386599/151656293-1c120590-3d91-42b5-af56-2457248916a6.png)

**Comment by irasin** [comment]
zip返回的迭代器的长度，会采取较短的一个输入作为最终的长度，因为你的style只有6张，所以当然只生成6对图片。

style我记得是用了另外一个数据集，里面的图片有很多，所以没有特别在意怎么处理，随便挑选了一些就训的。

你的这个情况，把这里的代码改一下应该就行了吧，不用zip，从content和style中分别抽样组成图片对就行了

**Comment by wangling9010** [comment]
好的，我懂啦，谢谢大佬！
